medicine_data = {
    "Hypertension": [
        {
            "name": "Amlodipine",
            "compound": "Amlodipine besylate",
            "uses": "Lower blood pressure",
            "side_effects": "Swelling, dizziness, fatigue",
            "department": "Cardiology",
        },
        {
            "name": "Lisinopril",
            "compound": "Lisinopril",
            "uses": "Treat high blood pressure and heart failure",
            "side_effects": "Cough, headache, dizziness",
            "department": "Cardiology",
        },
        {
            "name": "Hydrochlorothiazide",
            "compound": "Hydrochlorothiazide",
            "uses": "Diuretic to reduce blood pressure",
            "side_effects": "Electrolyte imbalance, dehydration",
            "department": "Cardiology",
        },
    ],
    "Acute Myocardial Infarction": [
        {
            "name": "Aspirin",
            "compound": "Acetylsalicylic Acid",
            "uses": "Prevent blood clot formation",
            "side_effects": "Stomach upset, bleeding",
            "department": "Cardiology",
        },
        {
            "name": "Clopidogrel",
            "compound": "Clopidogrel bisulfate",
            "uses": "Prevent clotting",
            "side_effects": "Bruising, bleeding",
            "department": "Cardiology",
        },
        {
            "name": "Nitroglycerin",
            "compound": "Nitroglycerin",
            "uses": "Relieve chest pain",
            "side_effects": "Headache, low blood pressure",
            "department": "Cardiology",
        },
    ],
    "Arrhythmia": [
        {
            "name": "Amiodarone",
            "compound": "Amiodarone hydrochloride",
            "uses": "Control abnormal heart rhythms",
            "side_effects": "Liver toxicity, thyroid issues",
            "department": "Cardiology",
        },
        {
            "name": "Metoprolol",
            "compound": "Metoprolol tartrate",
            "uses": "Beta-blocker to regulate heart rate",
            "side_effects": "Fatigue, dizziness",
            "department": "Cardiology",
        },
        {
            "name": "Flecainide",
            "compound": "Flecainide acetate",
            "uses": "Treat serious arrhythmias",
            "side_effects": "Dizziness, blurred vision",
            "department": "Cardiology",
        },
    ],
    "Heart Failure": [
        {
            "name": "Furosemide",
            "compound": "Furosemide",
            "uses": "Diuretic to reduce fluid overload",
            "side_effects": "Electrolyte imbalance, dehydration",
            "department": "Cardiology",
        },
        {
            "name": "Carvedilol",
            "compound": "Carvedilol",
            "uses": "Beta-blocker for heart function",
            "side_effects": "Fatigue, low blood pressure",
            "department": "Cardiology",
        },
        {
            "name": "Spironolactone",
            "compound": "Spironolactone",
            "uses": "Diuretic and potassium-sparing",
            "side_effects": "Hyperkalemia, dizziness",
            "department": "Cardiology",
        },
    ],
    "Atrial Fibrillation": [
        {
            "name": "Warfarin",
            "compound": "Warfarin sodium",
            "uses": "Prevent blood clots",
            "side_effects": "Bleeding, bruising",
            "department": "Cardiology",
        },
        {
            "name": "Dabigatran",
            "compound": "Dabigatran etexilate",
            "uses": "Anticoagulant to prevent stroke",
            "side_effects": "Bleeding",
            "department": "Cardiology",
        },
        {
            "name": "Metoprolol",
            "compound": "Metoprolol tartrate",
            "uses": "Control heart rate",
            "side_effects": "Fatigue, dizziness",
            "department": "Cardiology",
        },
    ],
    "Pericarditis": [
        {
            "name": "Ibuprofen",
            "compound": "Ibuprofen",
            "uses": "Reduce inflammation and pain",
            "side_effects": "Stomach upset, bleeding",
            "department": "Cardiology",
        },
        {
            "name": "Colchicine",
            "compound": "Colchicine",
            "uses": "Prevent recurrent pericarditis",
            "side_effects": "Diarrhea, nausea",
            "department": "Cardiology",
        },
        {
            "name": "Prednisone",
            "compound": "Prednisone",
            "uses": "Reduce severe inflammation",
            "side_effects": "Weight gain, high blood sugar",
            "department": "Cardiology",
        },
    ],
    "Cardiomyopathy": [
        {
            "name": "Beta-blockers",
            "compound": "Metoprolol",
            "uses": "Improve heart function",
            "side_effects": "Fatigue, dizziness",
            "department": "Cardiology",
        },
        {
            "name": "ACE inhibitors",
            "compound": "Lisinopril",
            "uses": "Lower blood pressure and reduce strain on heart",
            "side_effects": "Cough, low blood pressure",
            "department": "Cardiology",
        },
        {
            "name": "Diuretics",
            "compound": "Furosemide",
            "uses": "Reduce fluid overload",
            "side_effects": "Electrolyte imbalance, dehydration",
            "department": "Cardiology",
        },
    ],
    "Angina Pectoris": [
        {
            "name": "Nitroglycerin",
            "compound": "Nitroglycerin",
            "uses": "Relieve chest pain",
            "side_effects": "Headache, low blood pressure",
            "department": "Cardiology",
        },
        {
            "name": "Aspirin",
            "compound": "Acetylsalicylic Acid",
            "uses": "Prevent blood clot formation",
            "side_effects": "Stomach upset, bleeding",
            "department": "Cardiology",
        },
        {
            "name": "Beta-blockers",
            "compound": "Metoprolol",
            "uses": "Reduce heart workload",
            "side_effects": "Fatigue, dizziness",
            "department": "Cardiology",
        },
    ],
    "Endocarditis": [
        {
            "name": "Penicillin",
            "compound": "Penicillin G",
            "uses": "Treat bacterial infection",
            "side_effects": "Allergic reactions, nausea",
            "department": "Cardiology",
        },
        {
            "name": "Vancomycin",
            "compound": "Vancomycin",
            "uses": "Antibiotic for resistant bacteria",
            "side_effects": "Kidney issues, rash",
            "department": "Cardiology",
        },
        {
            "name": "Gentamicin",
            "compound": "Gentamicin",
            "uses": "Treat bacterial infections",
            "side_effects": "Kidney toxicity, hearing loss",
            "department": "Cardiology",
        },
    ],
    "Cardiac Arrest": [
        {
            "name": "Epinephrine",
            "compound": "Epinephrine",
            "uses": "Stimulate heart during arrest",
            "side_effects": "Increased heart rate, high blood pressure",
            "department": "Emergency",
        },
        {
            "name": "Amiodarone",
            "compound": "Amiodarone hydrochloride",
            "uses": "Stabilize abnormal heart rhythms",
            "side_effects": "Liver toxicity, thyroid issues",
            "department": "Emergency",
        },
        {
            "name": "Lidocaine",
            "compound": "Lidocaine",
            "uses": "Antiarrhythmic agent",
            "side_effects": "Dizziness, numbness",
            "department": "Emergency",
        },
    ],
    "Pulmonary Embolism": [
        {
            "name": "Heparin",
            "compound": "Unfractionated Heparin",
            "uses": "Prevent blood clot growth",
            "side_effects": "Bleeding, bruising",
            "department": "Emergency",
        },
        {
            "name": "Warfarin",
            "compound": "Warfarin sodium",
            "uses": "Prevent further clots",
            "side_effects": "Bleeding, nausea",
            "department": "Emergency",
        },
        {
            "name": "Rivaroxaban",
            "compound": "Rivaroxaban",
            "uses": "Oral anticoagulant",
            "side_effects": "Bleeding, anemia",
            "department": "Emergency",
        },
    ],
    "Aortic Aneurysm": [
        {
            "name": "Beta-blockers",
            "compound": "Metoprolol",
            "uses": "Reduce blood pressure and aortic stress",
            "side_effects": "Fatigue, dizziness",
            "department": "Cardiology",
        },
        {
            "name": "ACE inhibitors",
            "compound": "Lisinopril",
            "uses": "Lower blood pressure",
            "side_effects": "Cough, low blood pressure",
            "department": "Cardiology",
        },
        {
            "name": "Losartan",
            "compound": "Losartan",
            "uses": "Prevent aneurysm growth",
            "side_effects": "Dizziness, headache",
            "department": "Cardiology",
        },
    ],
    "Aortic Stenosis": [
        {
            "name": "Beta-blockers",
            "compound": "Atenolol",
            "uses": "Reduce heart workload",
            "side_effects": "Fatigue, dizziness",
            "department": "Cardiology",
        },
        {
            "name": "Diuretics",
            "compound": "Furosemide",
            "uses": "Reduce fluid overload",
            "side_effects": "Electrolyte imbalance, dehydration",
            "department": "Cardiology",
        },
        {
            "name": "Statins",
            "compound": "Atorvastatin",
            "uses": "Lower cholesterol",
            "side_effects": "Muscle pain, liver issues",
            "department": "Cardiology",
        },
    ],
    "Mitral Valve Prolapse": [
        {
            "name": "Beta-blockers",
            "compound": "Propranolol",
            "uses": "Control palpitations and chest pain",
            "side_effects": "Fatigue, dizziness",
            "department": "Cardiology",
        },
        {
            "name": "Aspirin",
            "compound": "Acetylsalicylic Acid",
            "uses": "Prevent clot formation",
            "side_effects": "Stomach upset, bleeding",
            "department": "Cardiology",
        },
        {
            "name": "Diuretics",
            "compound": "Furosemide",
            "uses": "Reduce fluid retention",
            "side_effects": "Electrolyte imbalance, dehydration",
            "department": "Cardiology",
        },
    ],
    "Anaphylactic Shock": [
        {
            "name": "Epinephrine",
            "compound": "Epinephrine",
            "uses": "Immediate treatment for severe allergic reaction",
            "side_effects": "Rapid heart rate, anxiety",
            "department": "Emergency",
        },
        {
            "name": "Diphenhydramine",
            "compound": "Diphenhydramine hydrochloride",
            "uses": "Reduce allergic symptoms",
            "side_effects": "Drowsiness, dry mouth",
            "department": "Emergency",
        },
        {
            "name": "Hydrocortisone",
            "compound": "Hydrocortisone",
            "uses": "Reduce inflammation",
            "side_effects": "High blood sugar, fluid retention",
            "department": "Emergency",
        },
    ],
    "Traumatic Injury": [
        {
            "name": "Morphine",
            "compound": "Morphine sulfate",
            "uses": "Pain management",
            "side_effects": "Drowsiness, nausea",
            "department": "Emergency",
        },
        {
            "name": "Acetaminophen",
            "compound": "Paracetamol",
            "uses": "Mild to moderate pain relief",
            "side_effects": "Liver toxicity in high doses",
            "department": "Emergency",
        },
        {
            "name": "Ibuprofen",
            "compound": "Ibuprofen",
            "uses": "Reduce pain and inflammation",
            "side_effects": "Stomach upset, bleeding",
            "department": "Emergency",
        },
    ],
    "Septic Shock": [
        {
            "name": "Broad-spectrum antibiotics",
            "compound": "Meropenem",
            "uses": "Treat bacterial infection",
            "side_effects": "Diarrhea, nausea",
            "department": "Emergency",
        },
        {
            "name": "Norepinephrine",
            "compound": "Norepinephrine",
            "uses": "Maintain blood pressure",
            "side_effects": "Arrhythmias, high blood pressure",
            "department": "Emergency",
        },
        {
            "name": "Hydrocortisone",
            "compound": "Hydrocortisone",
            "uses": "Reduce inflammation",
            "side_effects": "High blood sugar, fluid retention",
            "department": "Emergency",
        },
    ],
    "Acute Asthma Exacerbation": [
        {
            "name": "Albuterol",
            "compound": "Albuterol sulfate",
            "uses": "Relieve bronchospasm",
            "side_effects": "Tremor, palpitations",
            "department": "Pediatrics",
        },
        {
            "name": "Prednisone",
            "compound": "Prednisone",
            "uses": "Reduce airway inflammation",
            "side_effects": "Weight gain, mood changes",
            "department": "Pediatrics",
        },
        {
            "name": "Ipratropium",
            "compound": "Ipratropium bromide",
            "uses": "Bronchodilator",
            "side_effects": "Dry mouth, cough",
            "department": "Pediatrics",
        },
    ],
    "Stroke": [
        {
            "name": "Alteplase",
            "compound": "Recombinant tissue plasminogen activator",
            "uses": "Dissolve blood clots",
            "side_effects": "Bleeding, hypotension",
            "department": "Neurology",
        },
        {
            "name": "Aspirin",
            "compound": "Acetylsalicylic Acid",
            "uses": "Prevent further clot formation",
            "side_effects": "Stomach upset, bleeding",
            "department": "Neurology",
        },
        {
            "name": "Clopidogrel",
            "compound": "Clopidogrel bisulfate",
            "uses": "Prevent clot formation",
            "side_effects": "Bruising, bleeding",
            "department": "Neurology",
        },
    ],
    "Hypoglycemia": [
        {
            "name": "Glucose",
            "compound": "Dextrose",
            "uses": "Increase blood sugar rapidly",
            "side_effects": "Hyperglycemia if overdosed",
            "department": "Internal Medicine",
        },
        {
            "name": "Glucagon",
            "compound": "Glucagon",
            "uses": "Emergency treatment for severe hypoglycemia",
            "side_effects": "Nausea, vomiting",
            "department": "Internal Medicine",
        },
        {
            "name": "Oral sugar solution",
            "compound": "Sucrose solution",
            "uses": "Mild hypoglycemia treatment",
            "side_effects": "Tooth decay if frequent",
            "department": "Internal Medicine",
        },
    ],
    "Hyperglycemic Crisis": [
        {
            "name": "Insulin",
            "compound": "Regular Insulin",
            "uses": "Lower high blood sugar",
            "side_effects": "Hypoglycemia, low potassium",
            "department": "Internal Medicine",
        },
        {
            "name": "IV fluids",
            "compound": "Normal saline",
            "uses": "Rehydrate patient",
            "side_effects": "Fluid overload",
            "department": "Internal Medicine",
        },
        {
            "name": "Potassium chloride",
            "compound": "Potassium chloride",
            "uses": "Correct electrolyte imbalance",
            "side_effects": "Hyperkalemia if overdosed",
            "department": "Internal Medicine",
        },
    ],
    "Heat Stroke": [
        {
            "name": "IV fluids",
            "compound": "Normal saline",
            "uses": "Rehydrate patient",
            "side_effects": "Fluid overload",
            "department": "Emergency",
        },
        {
            "name": "Cooling therapy",
            "compound": "Ice packs / Cooling blankets",
            "uses": "Reduce body temperature",
            "side_effects": "Shivering, discomfort",
            "department": "Emergency",
        },
        {
            "name": "Electrolyte replacement",
            "compound": "Sodium/potassium solutions",
            "uses": "Correct dehydration",
            "side_effects": "Electrolyte imbalance if overdosed",
            "department": "Emergency",
        },
    ],
    "Alcohol Poisoning": [
        {
            "name": "IV fluids",
            "compound": "Normal saline",
            "uses": "Hydration",
            "side_effects": "Fluid overload",
            "department": "Emergency",
        },
        {
            "name": "Thiamine",
            "compound": "Vitamin B1",
            "uses": "Prevent Wernicke’s encephalopathy",
            "side_effects": "Allergic reaction rare",
            "department": "Emergency",
        },
        {
            "name": "Activated charcoal",
            "compound": "Activated charcoal",
            "uses": "Reduce alcohol absorption",
            "side_effects": "Nausea, vomiting",
            "department": "Emergency",
        },
    ],
    "Drug Overdose": [
        {
            "name": "Activated charcoal",
            "compound": "Activated charcoal",
            "uses": "Prevent absorption of ingested toxins",
            "side_effects": "Nausea, vomiting",
            "department": "Emergency",
        },
        {
            "name": "Naloxone",
            "compound": "Naloxone hydrochloride",
            "uses": "Reverse opioid overdose",
            "side_effects": "Withdrawal symptoms, nausea",
            "department": "Emergency",
        },
        {
            "name": "Supportive care",
            "compound": "IV fluids, oxygen",
            "uses": "Stabilize vital signs",
            "side_effects": "Fluid overload if excessive",
            "department": "Emergency",
        },
    ],
    "Poisoning": [
        {
            "name": "Activated charcoal",
            "compound": "Activated charcoal",
            "uses": "Absorb toxin",
            "side_effects": "Nausea, vomiting",
            "department": "Emergency",
        },
        {
            "name": "N-acetylcysteine",
            "compound": "N-acetylcysteine",
            "uses": "Antidote for acetaminophen overdose",
            "side_effects": "Rash, nausea",
            "department": "Emergency",
        },
        {
            "name": "Supportive care",
            "compound": "IV fluids, oxygen",
            "uses": "Stabilize patient",
            "side_effects": "Fluid overload if excessive",
            "department": "Emergency",
        },
    ],
    "Appendicitis": [
        {
            "name": "Ceftriaxone",
            "compound": "Ceftriaxone",
            "uses": "Pre-surgery antibiotic",
            "side_effects": "Diarrhea, rash",
            "department": "Emergency",
        },
        {
            "name": "Metronidazole",
            "compound": "Metronidazole",
            "uses": "Treat anaerobic bacteria",
            "side_effects": "Nausea, metallic taste",
            "department": "Emergency",
        },
        {
            "name": "Pain relievers",
            "compound": "Acetaminophen",
            "uses": "Reduce pain",
            "side_effects": "Liver toxicity if overdosed",
            "department": "Emergency",
        },
    ],
    "Type 2 Diabetes": [
        {
            "name": "Metformin",
            "compound": "Metformin hydrochloride",
            "uses": "Lower blood sugar",
            "side_effects": "GI upset, lactic acidosis rare",
            "department": "Internal Medicine",
        },
        {
            "name": "Glimepiride",
            "compound": "Glimepiride",
            "uses": "Stimulate insulin secretion",
            "side_effects": "Hypoglycemia, weight gain",
            "department": "Internal Medicine",
        },
        {
            "name": "Sitagliptin",
            "compound": "Sitagliptin phosphate",
            "uses": "Increase insulin release",
            "side_effects": "Pancreatitis, headache",
            "department": "Internal Medicine",
        },
    ],
    "Pneumonia": [
        {
            "name": "Amoxicillin",
            "compound": "Amoxicillin",
            "uses": "Treat bacterial pneumonia",
            "side_effects": "Diarrhea, rash",
            "department": "Internal Medicine",
        },
        {
            "name": "Azithromycin",
            "compound": "Azithromycin",
            "uses": "Treat atypical pneumonia",
            "side_effects": "GI upset, liver issues",
            "department": "Internal Medicine",
        },
        {
            "name": "Cefuroxime",
            "compound": "Cefuroxime",
            "uses": "Broad-spectrum antibiotic",
            "side_effects": "Diarrhea, allergic reaction",
            "department": "Internal Medicine",
        },
    ],
    "Anemia": [
        {
            "name": "Ferrous sulfate",
            "compound": "Ferrous sulfate",
            "uses": "Iron supplementation",
            "side_effects": "Constipation, nausea",
            "department": "Internal Medicine",
        },
        {
            "name": "Vitamin B12",
            "compound": "Cyanocobalamin",
            "uses": "Treat B12 deficiency",
            "side_effects": "Injection site reaction, headache",
            "department": "Internal Medicine",
        },
        {
            "name": "Folic acid",
            "compound": "Folic acid",
            "uses": "Treat folate deficiency",
            "side_effects": "Rare allergic reactions",
            "department": "Internal Medicine",
        },
    ],
    "COPD": [
        {
            "name": "Albuterol",
            "compound": "Albuterol sulfate",
            "uses": "Relieve bronchospasm",
            "side_effects": "Tremor, palpitations",
            "department": "Internal Medicine",
        },
        {
            "name": "Ipratropium",
            "compound": "Ipratropium bromide",
            "uses": "Bronchodilator",
            "side_effects": "Dry mouth, cough",
            "department": "Internal Medicine",
        },
        {
            "name": "Prednisone",
            "compound": "Prednisone",
            "uses": "Reduce airway inflammation",
            "side_effects": "Weight gain, mood changes",
            "department": "Internal Medicine",
        },
    ],
    "GERD": [
        {
            "name": "Omeprazole",
            "compound": "Omeprazole",
            "uses": "Reduce stomach acid",
            "side_effects": "Headache, nausea",
            "department": "Internal Medicine",
        },
        {
            "name": "Ranitidine",
            "compound": "Ranitidine",
            "uses": "H2 receptor blocker",
            "side_effects": "GI upset, headache",
            "department": "Internal Medicine",
        },
        {
            "name": "Antacids",
            "compound": "Aluminum hydroxide / Magnesium hydroxide",
            "uses": "Neutralize stomach acid",
            "side_effects": "Constipation, diarrhea",
            "department": "Internal Medicine",
        },
    ],
    "Thyroid Disorders": [
        {
            "name": "Levothyroxine",
            "compound": "Levothyroxine sodium",
            "uses": "Replace thyroid hormone",
            "side_effects": "Palpitations, weight loss",
            "department": "Internal Medicine",
        },
        {
            "name": "Methimazole",
            "compound": "Methimazole",
            "uses": "Reduce thyroid hormone production",
            "side_effects": "Rash, liver toxicity",
            "department": "Internal Medicine",
        },
        {
            "name": "Propylthiouracil",
            "compound": "Propylthiouracil",
            "uses": "Control hyperthyroidism",
            "side_effects": "Liver toxicity, nausea",
            "department": "Internal Medicine",
        },
    ],
    "Rheumatoid Arthritis": [
        {
            "name": "Methotrexate",
            "compound": "Methotrexate",
            "uses": "Reduce inflammation and slow disease progression",
            "side_effects": "Liver toxicity, nausea",
            "department": "Internal Medicine",
        },
        {
            "name": "Hydroxychloroquine",
            "compound": "Hydroxychloroquine",
            "uses": "Reduce immune system activity",
            "side_effects": "Retinal toxicity, headache",
            "department": "Internal Medicine",
        },
        {
            "name": "Prednisone",
            "compound": "Prednisone",
            "uses": "Control flare-ups",
            "side_effects": "Weight gain, mood changes",
            "department": "Internal Medicine",
        },
    ],
    "Chronic Kidney Disease": [
        {
            "name": "Lisinopril",
            "compound": "Lisinopril",
            "uses": "Lower blood pressure and protect kidneys",
            "side_effects": "Cough, dizziness",
            "department": "Internal Medicine",
        },
        {
            "name": "Furosemide",
            "compound": "Furosemide",
            "uses": "Reduce fluid overload",
            "side_effects": "Electrolyte imbalance, dehydration",
            "department": "Internal Medicine",
        },
        {
            "name": "Erythropoietin",
            "compound": "Epoetin alfa",
            "uses": "Treat anemia associated with CKD",
            "side_effects": "High blood pressure, headache",
            "department": "Internal Medicine",
        },
    ],
    "Liver Cirrhosis": [
        {
            "name": "Spironolactone",
            "compound": "Spironolactone",
            "uses": "Reduce fluid retention",
            "side_effects": "Hyperkalemia, dizziness",
            "department": "Internal Medicine",
        },
        {
            "name": "Furosemide",
            "compound": "Furosemide",
            "uses": "Diuretic to control edema",
            "side_effects": "Electrolyte imbalance, dehydration",
            "department": "Internal Medicine",
        },
        {
            "name": "Lactulose",
            "compound": "Lactulose",
            "uses": "Reduce ammonia levels in hepatic encephalopathy",
            "side_effects": "Diarrhea, bloating",
            "department": "Internal Medicine",
        },
    ],
    "Peptic Ulcer": [
        {
            "name": "Omeprazole",
            "compound": "Omeprazole",
            "uses": "Reduce stomach acid",
            "side_effects": "Headache, nausea",
            "department": "Internal Medicine",
        },
        {
            "name": "Amoxicillin",
            "compound": "Amoxicillin",
            "uses": "Treat H. pylori infection",
            "side_effects": "Diarrhea, rash",
            "department": "Internal Medicine",
        },
        {
            "name": "Clarithromycin",
            "compound": "Clarithromycin",
            "uses": "Treat H. pylori infection",
            "side_effects": "GI upset, taste disturbance",
            "department": "Internal Medicine",
        },
    ],
    "Influenza": [
        {
            "name": "Oseltamivir",
            "compound": "Oseltamivir phosphate",
            "uses": "Reduce severity of flu symptoms",
            "side_effects": "Nausea, vomiting",
            "department": "Internal Medicine",
        },
        {
            "name": "Acetaminophen",
            "compound": "Paracetamol",
            "uses": "Reduce fever and pain",
            "side_effects": "Liver toxicity in high doses",
            "department": "Internal Medicine",
        },
        {
            "name": "Zanamivir",
            "compound": "Zanamivir",
            "uses": "Antiviral therapy",
            "side_effects": "Throat irritation, cough",
            "department": "Internal Medicine",
        },
    ],
    "Gout": [
        {
            "name": "Allopurinol",
            "compound": "Allopurinol",
            "uses": "Lower uric acid levels",
            "side_effects": "Rash, liver issues",
            "department": "Internal Medicine",
        },
        {
            "name": "Colchicine",
            "compound": "Colchicine",
            "uses": "Treat acute gout flare-ups",
            "side_effects": "Diarrhea, nausea",
            "department": "Internal Medicine",
        },
        {
            "name": "NSAIDs",
            "compound": "Ibuprofen",
            "uses": "Reduce pain and inflammation",
            "side_effects": "Stomach upset, bleeding",
            "department": "Internal Medicine",
        },
    ],
    "Acute Otitis Media": [
        {
            "name": "Amoxicillin",
            "compound": "Amoxicillin",
            "uses": "Treat bacterial ear infection",
            "side_effects": "Diarrhea, rash",
            "department": "Pediatrics",
        },
        {
            "name": "Cefuroxime",
            "compound": "Cefuroxime",
            "uses": "Alternative antibiotic",
            "side_effects": "Diarrhea, allergic reactions",
            "department": "Pediatrics",
        },
        {
            "name": "Acetaminophen",
            "compound": "Paracetamol",
            "uses": "Pain and fever relief",
            "side_effects": "Liver toxicity in high doses",
            "department": "Pediatrics",
        },
    ],
    "Bronchiolitis": [
        {
            "name": "Albuterol",
            "compound": "Albuterol sulfate",
            "uses": "Relieve wheezing",
            "side_effects": "Tremor, palpitations",
            "department": "Pediatrics",
        },
        {
            "name": "Oxygen therapy",
            "compound": "Oxygen",
            "uses": "Maintain oxygen saturation",
            "side_effects": "Dryness of nasal passages",
            "department": "Pediatrics",
        },
        {
            "name": "Hypertonic saline",
            "compound": "3% saline",
            "uses": "Aid mucus clearance",
            "side_effects": "Cough, throat irritation",
            "department": "Pediatrics",
        },
    ],
    "Croup": [
        {
            "name": "Dexamethasone",
            "compound": "Dexamethasone",
            "uses": "Reduce airway inflammation",
            "side_effects": "Mood changes, increased blood sugar",
            "department": "Pediatrics",
        },
        {
            "name": "Nebulized Epinephrine",
            "compound": "Racemic Epinephrine",
            "uses": "Reduce airway swelling",
            "side_effects": "Tachycardia, anxiety",
            "department": "Pediatrics",
        },
        {
            "name": "Oxygen therapy",
            "compound": "Oxygen",
            "uses": "Maintain oxygen saturation",
            "side_effects": "Nasal dryness",
            "department": "Pediatrics",
        },
    ],
    "Gastroenteritis": [
        {
            "name": "Oral Rehydration Solution",
            "compound": "ORS",
            "uses": "Prevent dehydration",
            "side_effects": "Overhydration rare",
            "department": "Pediatrics",
        },
        {
            "name": "Zinc supplements",
            "compound": "Zinc sulfate",
            "uses": "Support immune recovery",
            "side_effects": "Nausea, metallic taste",
            "department": "Pediatrics",
        },
        {
            "name": "Antiemetics",
            "compound": "Ondansetron",
            "uses": "Reduce vomiting",
            "side_effects": "Headache, constipation",
            "department": "Pediatrics",
        },
    ],
    "Tonsillitis": [
        {
            "name": "Amoxicillin",
            "compound": "Amoxicillin",
            "uses": "Treat bacterial infection",
            "side_effects": "Diarrhea, rash",
            "department": "ENT",
        },
        {
            "name": "Penicillin V",
            "compound": "Penicillin V potassium",
            "uses": "Treat bacterial tonsillitis",
            "side_effects": "Allergic reactions, nausea",
            "department": "ENT",
        },
        {
            "name": "Acetaminophen",
            "compound": "Paracetamol",
            "uses": "Pain and fever relief",
            "side_effects": "Liver toxicity in high doses",
            "department": "ENT",
        },
    ],
    "Measles": [
        {
            "name": "Vitamin A",
            "compound": "Retinol",
            "uses": "Support immune recovery",
            "side_effects": "Headache, nausea",
            "department": "Pediatrics",
        },
        {
            "name": "Acetaminophen",
            "compound": "Paracetamol",
            "uses": "Reduce fever and pain",
            "side_effects": "Liver toxicity in high doses",
            "department": "Pediatrics",
        },
        {
            "name": "Supportive care",
            "compound": "Fluids and rest",
            "uses": "Symptom relief",
            "side_effects": "None",
            "department": "Pediatrics",
        },
    ],
    "Mumps": [
        {
            "name": "Acetaminophen",
            "compound": "Paracetamol",
            "uses": "Reduce pain and fever",
            "side_effects": "Liver toxicity in high doses",
            "department": "Pediatrics",
        },
        {
            "name": "Ibuprofen",
            "compound": "Ibuprofen",
            "uses": "Reduce pain and inflammation",
            "side_effects": "Stomach upset, bleeding",
            "department": "Pediatrics",
        },
        {
            "name": "Supportive care",
            "compound": "Fluids and rest",
            "uses": "Symptom relief",
            "side_effects": "None",
            "department": "Pediatrics",
        },
    ],
    "Chickenpox": [
        {
            "name": "Acyclovir",
            "compound": "Acyclovir",
            "uses": "Antiviral therapy",
            "side_effects": "Nausea, headache",
            "department": "Pediatrics",
        },
        {
            "name": "Calamine lotion",
            "compound": "Calamine",
            "uses": "Relieve itching",
            "side_effects": "Skin irritation rare",
            "department": "Pediatrics",
        },
        {
            "name": "Acetaminophen",
            "compound": "Paracetamol",
            "uses": "Reduce fever and pain",
            "side_effects": "Liver toxicity in high doses",
            "department": "Pediatrics",
        },
    ],
    "Asthma (Childhood)": [
        {
            "name": "Albuterol",
            "compound": "Albuterol sulfate",
            "uses": "Relieve bronchospasm",
            "side_effects": "Tremor, palpitations",
            "department": "Pediatrics",
        },
        {
            "name": "Fluticasone",
            "compound": "Fluticasone propionate",
            "uses": "Reduce airway inflammation",
            "side_effects": "Thrush, hoarseness",
            "department": "Pediatrics",
        },
        {
            "name": "Montelukast",
            "compound": "Montelukast sodium",
            "uses": "Prevent asthma attacks",
            "side_effects": "Headache, abdominal pain",
            "department": "Pediatrics",
        },
    ],
    "Congenital Heart Disease": [
        {
            "name": "Furosemide",
            "compound": "Furosemide",
            "uses": "Reduce fluid overload",
            "side_effects": "Electrolyte imbalance, dehydration",
            "department": "Cardiology",
        },
        {
            "name": "Digoxin",
            "compound": "Digoxin",
            "uses": "Improve heart function",
            "side_effects": "Arrhythmias, nausea",
            "department": "Cardiology",
        },
        {
            "name": "Propranolol",
            "compound": "Propranolol",
            "uses": "Control heart rate",
            "side_effects": "Fatigue, dizziness",
            "department": "Cardiology",
        },
    ],
    "Neonatal Jaundice": [
        {
            "name": "Phototherapy",
            "compound": "Blue light therapy",
            "uses": "Break down bilirubin",
            "side_effects": "Dehydration, rash",
            "department": "Pediatrics",
        },
        {
            "name": "IV fluids",
            "compound": "Dextrose solution",
            "uses": "Maintain hydration",
            "side_effects": "Fluid overload if excessive",
            "department": "Pediatrics",
        },
        {
            "name": "Exchange transfusion",
            "compound": "Whole blood exchange",
            "uses": "Severe cases of hyperbilirubinemia",
            "side_effects": "Blood reaction risk",
            "department": "Pediatrics",
        },
    ],
    "Failure to Thrive": [
        {
            "name": "Nutritional supplements",
            "compound": "High-calorie formula",
            "uses": "Promote weight gain",
            "side_effects": "Diarrhea, constipation",
            "department": "Pediatrics",
        },
        {
            "name": "Multivitamins",
            "compound": "Vitamin blend",
            "uses": "Address deficiencies",
            "side_effects": "Nausea, vomiting",
            "department": "Pediatrics",
        },
        {
            "name": "Feeding therapy",
            "compound": "Special diet plan",
            "uses": "Improve caloric intake",
            "side_effects": "None",
            "department": "Pediatrics",
        },
    ],
    "Pregnancy-Related Anemia": [
        {
            "name": "Ferrous sulfate",
            "compound": "Ferrous sulfate",
            "uses": "Increase iron levels",
            "side_effects": "Constipation, nausea",
            "department": "Gynecology & Obstetrics",
        },
        {
            "name": "Folic acid",
            "compound": "Folic acid",
            "uses": "Prevent neural tube defects and treat anemia",
            "side_effects": "Rare allergic reactions",
            "department": "Gynecology & Obstetrics",
        },
        {
            "name": "Vitamin B12",
            "compound": "Cyanocobalamin",
            "uses": "Treat B12 deficiency",
            "side_effects": "Injection site reactions",
            "department": "Gynecology & Obstetrics",
        },
    ],
    "Gestational Diabetes": [
        {
            "name": "Insulin",
            "compound": "Regular Insulin",
            "uses": "Control blood sugar",
            "side_effects": "Hypoglycemia, weight gain",
            "department": "Gynecology & Obstetrics",
        },
        {
            "name": "Metformin",
            "compound": "Metformin hydrochloride",
            "uses": "Lower blood sugar",
            "side_effects": "GI upset, nausea",
            "department": "Gynecology & Obstetrics",
        },
        {
            "name": "Diet modification",
            "compound": "Low sugar, high fiber diet",
            "uses": "Manage blood sugar",
            "side_effects": "None",
            "department": "Gynecology & Obstetrics",
        },
    ],
    "Preeclampsia": [
        {
            "name": "Labetalol",
            "compound": "Labetalol hydrochloride",
            "uses": "Lower blood pressure",
            "side_effects": "Fatigue, dizziness",
            "department": "Gynecology & Obstetrics",
        },
        {
            "name": "Hydralazine",
            "compound": "Hydralazine hydrochloride",
            "uses": "Control severe hypertension",
            "side_effects": "Headache, tachycardia",
            "department": "Gynecology & Obstetrics",
        },
        {
            "name": "Magnesium sulfate",
            "compound": "Magnesium sulfate",
            "uses": "Prevent seizures",
            "side_effects": "Flushing, nausea",
            "department": "Gynecology & Obstetrics",
        },
    ],
    "Ectopic Pregnancy": [
        {
            "name": "Methotrexate",
            "compound": "Methotrexate",
            "uses": "Terminate ectopic pregnancy medically",
            "side_effects": "Nausea, liver toxicity",
            "department": "Gynecology & Obstetrics",
        },
        {
            "name": "Pain relievers",
            "compound": "Acetaminophen",
            "uses": "Reduce pain",
            "side_effects": "Liver toxicity if overdosed",
            "department": "Gynecology & Obstetrics",
        },
        {
            "name": "Surgery",
            "compound": "Laparoscopy",
            "uses": "Remove ectopic pregnancy",
            "side_effects": "Surgical risks",
            "department": "Gynecology & Obstetrics",
        },
    ],
    "Polycystic Ovarian Syndrome": [
        {
            "name": "Metformin",
            "compound": "Metformin hydrochloride",
            "uses": "Improve insulin sensitivity",
            "side_effects": "GI upset, nausea",
            "department": "Gynecology & Obstetrics",
        },
        {
            "name": "Oral contraceptives",
            "compound": "Ethinylestradiol + Drospirenone",
            "uses": "Regulate menstrual cycles",
            "side_effects": "Nausea, headache",
            "department": "Gynecology & Obstetrics",
        },
        {
            "name": "Clomiphene",
            "compound": "Clomiphene citrate",
            "uses": "Induce ovulation",
            "side_effects": "Hot flashes, mood changes",
            "department": "Gynecology & Obstetrics",
        },
    ],
    "Endometriosis": [
        {
            "name": "GnRH agonists",
            "compound": "Leuprolide",
            "uses": "Reduce estrogen and endometrial growth",
            "side_effects": "Hot flashes, bone loss",
            "department": "Gynecology & Obstetrics",
        },
        {
            "name": "NSAIDs",
            "compound": "Ibuprofen",
            "uses": "Pain relief",
            "side_effects": "Stomach upset, bleeding",
            "department": "Gynecology & Obstetrics",
        },
        {
            "name": "Hormonal contraceptives",
            "compound": "Ethinylestradiol + Progestin",
            "uses": "Regulate cycles and reduce pain",
            "side_effects": "Nausea, weight gain",
            "department": "Gynecology & Obstetrics",
        },
    ],
    "Vaginitis": [
        {
            "name": "Metronidazole",
            "compound": "Metronidazole",
            "uses": "Treat bacterial vaginosis",
            "side_effects": "Nausea, metallic taste",
            "department": "Gynecology & Obstetrics",
        },
        {
            "name": "Clotrimazole",
            "compound": "Clotrimazole",
            "uses": "Treat yeast infections",
            "side_effects": "Vaginal irritation, burning",
            "department": "Gynecology & Obstetrics",
        },
        {
            "name": "Probiotics",
            "compound": "Lactobacillus",
            "uses": "Restore normal flora",
            "side_effects": "Mild GI upset",
            "department": "Gynecology & Obstetrics",
        },
    ],
    "Menorrhagia": [
        {
            "name": "Tranexamic acid",
            "compound": "Tranexamic acid",
            "uses": "Reduce heavy bleeding",
            "side_effects": "Nausea, headache",
            "department": "Gynecology & Obstetrics",
        },
        {
            "name": "NSAIDs",
            "compound": "Ibuprofen",
            "uses": "Reduce pain and bleeding",
            "side_effects": "Stomach upset, bleeding",
            "department": "Gynecology & Obstetrics",
        },
        {
            "name": "Oral contraceptives",
            "compound": "Ethinylestradiol + Progestin",
            "uses": "Regulate menstrual flow",
            "side_effects": "Nausea, weight gain",
            "department": "Gynecology & Obstetrics",
        },
    ],
    "Ovarian Cysts": [
        {
            "name": "Oral contraceptives",
            "compound": "Ethinylestradiol + Progestin",
            "uses": "Prevent formation of new cysts",
            "side_effects": "Nausea, weight gain",
            "department": "Gynecology & Obstetrics",
        },
        {
            "name": "NSAIDs",
            "compound": "Ibuprofen",
            "uses": "Pain relief",
            "side_effects": "Stomach upset, bleeding",
            "department": "Gynecology & Obstetrics",
        },
        {
            "name": "Surgery",
            "compound": "Laparoscopy",
            "uses": "Remove cyst if large or symptomatic",
            "side_effects": "Surgical risks",
            "department": "Gynecology & Obstetrics",
        },
    ],
}
