staff_data = [
    "staff_id",
    "first_name",
    "last_name",
    "full_name",
    "gender",
    "age",
    "contact_number",
    "role",
    "department",
    "specialization",
    "qualification",
    "years_experience",
    "shift",
    "hospital_id",
    "hospital_name",
    "city",
    "governorate",
    "on_leave",
]


department_roles = {
    "Emergency": ["Emergency Physician", "Nurse", "Paramedic", "Technician"],
    "Internal Medicine": ["General Practitioner", "Internist", "Nurse"],
    "General Surgery": ["Surgeon", "Surgical Nurse", "Anesthesiologist", "Technician"],
    "Pediatrics": ["Pediatrician", "Pediatric Nurse", "Technician"],
    "Gynecology & Obstetrics": ["Gynecologist", "Obstetrician", "Nurse", "Midwife"],
    "Radiology": ["Radiologist", "Radiology Technician"],
    "Laboratory": ["Pathologist", "Lab Technician"],
    "Cardiology": ["Cardiologist", "Cardiac Nurse", "Technician"],
    "Neurology": ["Neurologist", "Neuro Nurse", "Technician"],
    "Orthopedics": ["Orthopedic Surgeon", "Nurse", "Physiotherapist"],
    "Oncology": ["Oncologist", "Oncology Nurse", "Chemotherapy Technician"],
    "Urology": ["Urologist", "Nurse", "Technician"],
    "Dermatology": ["Dermatologist", "Nurse"],
    "ENT": ["ENT Specialist", "Nurse", "Technician"],
    "Ophthalmology": ["Ophthalmologist", "Nurse", "Technician"],
    "Psychiatry": ["Psychiatrist", "Psychology Counselor", "Nurse"],
    "Physical Therapy": ["Physiotherapist", "Rehabilitation Nurse"],
}


specialization_qualification = {
    "General Practitioner": "MD",
    "Internist": "MD",
    "Surgeon": "MD, Surgery Residency",
    "Pediatrician": "MD, Pediatrics Residency",
    "Gynecologist": "MD, OB/GYN Residency",
    "Obstetrician": "MD, OB/GYN Residency",
    "Radiologist": "MD, Radiology Residency",
    "Imaging Specialist": "BSc Radiology",
    "Lab Technician": "BSc Laboratory Sciences",
    "Pathologist": "MD, Pathology Residency",
    "Emergency Physician": "MD, Emergency Medicine Residency",
}
